apiVersion: v1
kind: ConfigMap
metadata:
  name: backtest-service-config
  namespace: stock-management
  labels:
    app: backtest-service
data:
  # Spring Boot 配置
  SPRING_PROFILES_ACTIVE: "k8s"  # k8s 專用配置檔
  
  # 服務間通信配置
  DATA_PROVIDER_URL: "http://data-provider-service:8000"  # 集群內服務名稱
  DATA_PROVIDER_TIMEOUT: "10000"  # 連接超時時間 (毫秒)
  
  # 應用配置
  SERVER_PORT: "8084"
  
  # 日誌配置
  LOGGING_LEVEL_ROOT: "INFO"  # 生產環境使用 INFO，調試時用 DEBUG
  LOGGING_PATTERN: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  # JVM 配置
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
  
  # Actuator 配置
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when_authorized"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  
  # 微服務配置
  SPRING_APPLICATION_NAME: "backtest-service"
  
  # 回測專用配置
  BACKTEST_MAX_STOCKS: "50"  # 單次回測最大股票數量
  BACKTEST_MAX_DAYS: "1830"   # 回測最大天數
  BACKTEST_CACHE_ENABLED: "true"  # 是否啟用快取