apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: stock-management
  labels:
    app: api-gateway
    tier: gateway
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_APPLICATION_NAME: "api-gateway"

  AUTH_SERVICE_URI: "http://auth-service:8081"
  ACCOUNT_SERVICE_URI: "http://account-service:8082"
  SUBSCRIBE_SERVICE_URI: "http://subscribe-service:8083"
  BACKTEST_SERVICE_URI: "http://backtest-service:8084"

  # 原本的特定 origin 設定（暫時註解用於測試）
  # CORS_ALLOWED_ORIGINS: "http://frontend.stock-management.local:8080"
  # 測試用設定：允許所有 origin
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"

  JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseContainerSupport"

  application-k8s.yml: |
    server:
      port: 8080
    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          globalcors:
            corsConfigurations:
              '[/**]':
                # 原本的特定 origin 設定（暫時註解用於測試）
                # allowedOrigins: "http://frontend.stock-management.local:8080"
                # allowCredentials: true
                # 測試用設定：允許所有 origin，但不包含 credentials
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: false
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**
            - id: account-service
              uri: http://account-service:8082
              predicates:
                - Path=/api/account/**
            - id: backtest-service
              uri: http://backtest-service:8084
              predicates:
                - Path=/api/backtest/**
            - id: subscribe-service
              uri: http://subscribe-service:8083
              predicates:
                - Path=/api/scanner/**
          locator:
            enabled: true
            lower-case-service-id: true
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
        reactor.netty.http.client: DEBUG
        com.stock_management.api_gateway.filter.JwtAuthenticationFilter: INFO