apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: stock-management
  labels:
    app: api-gateway
data:
  # 額外的 Spring 配置
  application-k8s.yml: |
    server:
      port: 8080
    
    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: 
                  - "http://frontend"        # 來自同一集群的前端服務
                  - "http://localhost:3000"  # 開發環境
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**
            - id: account-service
              uri: http://account-service:8082
              predicates:
                - Path=/api/account/**
            - id: backtest-service
              uri: http://backtest-service:8084
              predicates:
                - Path=/api/backtest/**
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
    
    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
        reactor.netty.http.client: DEBUG