apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: stock-management
  labels:
    app: api-gateway
    tier: gateway
  annotations:
    # 使用 nginx ingress controller
    ingressClassName: nginx

    # 關閉 HTTPS 自動 redirect（本地開發用）
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

    # Proxy timeout 設定
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: api.stock-management.local   # 本地測試
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
