apiVersion: v1
kind: ConfigMap
metadata:
  name: subscribe-service-config
  namespace: stock-management
  labels:
    app: subscribe-service
data:
  # Spring Boot 配置
  SPRING_PROFILES_ACTIVE: "k8s"  # k8s 專用配置檔
  
  # 服務間通信配置
  DATA_PROVIDER_URL: "http://data-provider-service:8000"  # 集群內服務名稱
  
  # 應用配置
  SERVER_PORT: "8083"
  
  # 日誌配置
  LOGGING_LEVEL_ROOT: "INFO"  # 生產環境使用 INFO，調試時用 DEBUG
  LOGGING_PATTERN: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  # JVM 配置
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
  
  # Actuator 配置
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when_authorized"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  
  # 微服務配置
  SPRING_APPLICATION_NAME: "subscribe-service"
  
  # 郵件 SMTP 配置 (非敏感部分)
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  
  # JPA 配置 (如果未來需要資料庫)
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"  # 生產環境建議關閉
  
  # 自動配置排除 (目前不使用資料庫)
  SPRING_AUTOCONFIGURE_EXCLUDE: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
  
  # Scanner 服務配置
  SCANNER_TIMEOUT: "30000"  # Scanner 請求超時時間 (毫秒)
  SCANNER_MAX_COUNT: "200"  # 最大掃描數量