apiVersion: v1
kind: Secret
metadata:
  name: subscribe-service-secret
  namespace: stock-management
  labels:
    app: subscribe-service
type: Opaque
data:
  # Gmail SMTP 認證 (base64 編碼)
  # 使用命令生成: echo -n "your-email@gmail.com" | base64
  GMAIL_USERNAME: "bWF0dDkxMDEwNkBnbWFpbC5jb20="  # matt910106@gmail.com 的 base64 編碼
  
  # Gmail App Password (base64 編碼)
  # 使用命令生成: echo -n "lltx spgv psfq wazn" | base64
  GMAIL_APP_PASSWORD: "bGx0eCBzcGd2IHBzZnEgd2F6bg=="  # lltx spgv psfq wazn 的 base64 編碼
  
  # JWT 配置 (base64 編碼) - 如果需要驗證 API Gateway 傳來的請求
  JWT_SECRET: "eW91ci1zZWNyZXQta2V5LWF0LWxlYXN0LTMyLWNoYXJhY3RlcnMtbG9uZw=="
  
  # 資料庫配置 (如果未來需要)
  # DB_USERNAME: "bXl1c2Vy"          # myuser 的 base64 編碼
  # DB_PASSWORD: "c2VjcmV0"          # secret 的 base64 編碼
  
  # 其他敏感配置
  # ENCRYPTION_KEY: "ZW5jcnlwdGlvbi1rZXk="
  
---
# ServiceAccount for subscribe-service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subscribe-service-sa
  namespace: stock-management
automountServiceAccountToken: false  # 安全性考量，除非需要 k8s API 訪問