apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribe-service
  namespace: stock-management
  labels:
    app: subscribe-service
    version: v1
spec:
  replicas: 1  # minikube 測試用，生產環境可調整為 2-3
  selector:
    matchLabels:
      app: subscribe-service
  template:
    metadata:
      labels:
        app: subscribe-service
        version: v1
    spec:
      serviceAccountName: subscribe-service-sa  # 使用自訂 ServiceAccount
      containers:
      - name: subscribe-service
        image: subscribe-service:latest  # 本地構建的映像
        imagePullPolicy: IfNotPresent  # minikube 使用本地映像，k3s 改為 Always
        ports:
        - containerPort: 8083
          name: http
          protocol: TCP
        env:
        # 從 ConfigMap 引用非敏感配置
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: SPRING_PROFILES_ACTIVE
        - name: DATA_PROVIDER_URL
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: DATA_PROVIDER_URL
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: SERVER_PORT
        - name: LOGGING_LEVEL_ROOT
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: LOGGING_LEVEL_ROOT
        - name: JAVA_TOOL_OPTIONS   # 改用 JAVA_TOOL_OPTIONS，K8s 常見做法
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: JAVA_OPTS
        # 郵件配置
        - name: SPRING_MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: SPRING_MAIL_HOST
        - name: SPRING_MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: SPRING_MAIL_PORT
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: subscribe-service-config
              key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        # 從 Secret 引用敏感配置
        - name: GMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: subscribe-service-secret
              key: GMAIL_USERNAME
        - name: GMAIL_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: subscribe-service-secret
              key: GMAIL_APP_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: subscribe-service-secret
              key: JWT_SECRET
              optional: true  # 如果 subscribe-service 不需要 JWT，設為可選
        # 健康檢查配置
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      initContainers:
      - name: wait-for-data-provider
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for data-provider service..."
          until nc -z data-provider-service 8000; do
            echo "data-provider not ready, waiting..."
            sleep 5
          done
          echo "data-provider is ready!"
      restartPolicy: Always
      dnsPolicy: ClusterFirst