services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user_service_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/user_service_db
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret
    depends_on:
      - postgres
      
volumes:
  postgres_data:
