services:
  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/user_service_db -user=myuser -password=secret migrate
    volumes:
      - ./backend/user_service/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user_service_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/user_service_db
      - DB_USERNAME=myuser
      - DB_PASSWORD=secret
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://user_service:8081 # 指向 user-service
    depends_on:
      - user_service

volumes:
  postgres_data:
