apiVersion: v1
kind: ConfigMap
metadata:
  name: data-provider-config
  namespace: stock-management
  labels:
    app: data-provider
data:
  # Python 應用配置
  PYTHONPATH: "/app"
  PYTHONUNBUFFERED: "1"  # 確保 Python 輸出不被緩衝
  
  # Gunicorn 配置
  GUNICORN_WORKERS: "1"  # 對於有狀態的 API 連線使用單一 worker
  GUNICORN_BIND: "0.0.0.0:8000"
  GUNICORN_TIMEOUT: "120"  # 股票資料請求可能較耗時
  GUNICORN_KEEPALIVE: "2"
  
  # 日誌配置
  LOG_LEVEL: "INFO"  # 生產環境使用 INFO，調試時用 DEBUG
  SJ_LOG_PATH: "/tmp/shioaji.log"  # Shioaji 日誌檔案路徑
  SJ_CONTRACTS_PATH: "/tmp"  # Shioaji 合約檔案存放路徑
  
  # FastAPI 配置
  FASTAPI_ENV: "production"
  FASTAPI_DEBUG: "false"
  
  # 應用程式配置
  APP_NAME: "data-provider"
  APP_VERSION: "0.1.0"
  APP_DESCRIPTION: "提供金融數據服務"
  
  # 資料處理配置
  MAX_SYMBOLS_PER_REQUEST: "50"  # 單次請求最大股票數量
  REQUEST_TIMEOUT: "300"         # 請求超時時間 (秒)
  CACHE_ENABLED: "true"          # 是否啟用快取
  CACHE_TTL: "300"               # 快取存活時間 (秒)
  
  # Shioaji 配置
  SHIOAJI_SIMULATION: "false"    # 是否使用模擬模式
  SHIOAJI_TIMEOUT: "30"          # Shioaji API 超時時間
  
  # 健康檢查配置
  HEALTH_CHECK_INTERVAL: "30"    # 健康檢查間隔 (秒)