server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**

        - id: account-service
          uri: http://account-service:8082
          predicates:
            - Path=/api/account/**
            
        - id: backtest-service
          uri: http://backtest-service:8084
          predicates:
            - Path=/api/backtest/**
            
        - id: subscribe-service
          uri: http://subscribe-service:8083
          predicates:
            - Path=/api/scanner/**

jwt:
  secret: ${JWT_SECRET:your-fallback-secret-key-at-least-32-characters-long}

