server:
  port: 8080 # Gateway 監聽的埠

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User Service 路由
        - id: user-service
          uri: http://user_service:8081
          predicates:
            - Path=/api/users/**
        # Account Service 路由
        - id: account-service
          uri: http://account_service:8082
          predicates:
            - Path=/api/accounts/**
        # Backtest Service 路由
        - id: backtest-service
          uri: http://backtest_service:8083
          predicates:
            - Path=/api/backtests/**
        # Subscribe Service 路由
        - id: subscribe-service
          uri: http://subscribe_service:8084
          predicates:
            - Path=/api/subscribes/** 