apiVersion: v1
kind: Service
metadata:
  name: account-service  # 其他服務通過此名稱訪問
  namespace: stock-management
  labels:
    app: account-service
    version: v1
spec:
  type: ClusterIP  # 僅集群內部訪問，不暴露到外部
  selector:
    app: account-service  # 選擇對應的 Pod
  ports:
  - name: http
    port: 8082        # 集群內其他服務訪問的端口
    targetPort: 8082  # Pod 內容器的端口
    protocol: TCP
  # 會話親和性配置（可選）
  sessionAffinity: None  # 或 ClientIP，根據需求調整
  # 服務發現配置
  publishNotReadyAddresses: false  # 只有就緒的 Pod 才會接收流量