apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: stock-management
  labels:
    app: postgres
    version: v1
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: stock-management
  labels:
    app: postgres
    version: v1
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres