apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: stock-management
  labels:
    app: postgres
    version: v1
type: Opaque
data:
  # 敏感信息 - base64 編碼
  # 注意：這些值需要根據實際環境設定
  # echo -n "your-actual-password" | base64
  POSTGRES_PASSWORD: "c3RvY2twYXNzMTIz"  # stockpass123 - 生產環境請更換！
  
  # 如果需要其他敏感配置，可以在此添加
  # POSTGRES_REPLICATION_PASSWORD: ""
  # POSTGRES_ADMIN_PASSWORD: ""