apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: stock-management  # 統一使用 stock-management 命名空間
  labels:
    app: auth-service
    version: v1
spec:
  replicas: 1  # minikube 測試用，生產環境可調整為 2-3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        version: v1
    spec:
      serviceAccountName: auth-service-sa  # 使用自訂 ServiceAccount
      containers:
      - name: auth-service
        image: matt15456/auth-service:latest  # Docker Hub映像
        imagePullPolicy: Always  # 總是拉取最新映像
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        env:
        # 從 ConfigMap 引用非敏感配置
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: SPRING_PROFILES_ACTIVE
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: DB_URL
        - name: JPA_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JPA_DDL_AUTO
        - name: JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JPA_SHOW_SQL
        - name: HIBERNATE_FORMAT_SQL
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: HIBERNATE_FORMAT_SQL
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: SERVER_PORT
        - name: LOGGING_LEVEL_ROOT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: LOGGING_LEVEL_ROOT
        - name: JAVA_TOOL_OPTIONS   # 改用 JAVA_TOOL_OPTIONS，K8s 常見做法
          valueFrom:
            configMapKeyRef:
              name: auth-service-config
              key: JAVA_OPTS
        # 從 Secret 引用敏感配置
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: JWT_SECRET
        # 健康檢查配置
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for postgres service..."
          until nc -z postgres-service 5432; do
            echo "postgres not ready, waiting..."
            sleep 5
          done
          echo "postgres is ready!"
      restartPolicy: Always
      dnsPolicy: ClusterFirst