#cloud-config
# 這是 cloud-init 配置檔，用於自動化 VM 啟動時的設定

# 1. SSH 設定：添加你的 SSH 公鑰，方便直接 SSH 登入 VM
users:
  - name: ubuntu # Multipass VM 預設的使用者名稱
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCk4X1e/7NnYQ+TZzB7FbX8SbJmJ4N8qungBquy812Bx17gPc29IPDd3t5+kPqz+WNpbmnYkQS2D8jbCxBh1w8DxiecLnxeQS9Bc80HQVx+Z+RaQQTp6/gtHbkYcHdgtbU5JaAMVZOAax10PJ3fRifymyH7TiTqedvEOfe18SCxQTwEeWy0UsoSnTUk29peJm52N5E6IxYOLTMBMjmqR9QQDJe5B/CIDAzyllRLyoUT1HmOQ7UhNgZZpLCXtnBlPwB8l4H+uPaIBy/AImlmN5fZ5FAaHljdR/66+1Bv2tlJdCTdEoXo81FY62JcqTiXq9QUcXtWMbP/JMaPUSXaaTxiiGQoW7Gm92gTwBhnDjPHaLVcx4klZrPrG+L46oDFxJp3bz9XGxrZr0c//rsa8CUSo0FzBu0FWfn0Gc/MeoVgzStvQjxJWmzJ+YjEugtaRbOgcMKXv0+idNWm++56+G47V0brTFIhjM80l9FtnijUWIcH2V47wDuuAre79UUYECcUqfcm99K3fYyzYGr4dckaExwNvqSEVg804g9h0JyBH5zrHVhBLmHwQXRMOujFDCDmjOzU5ua4DKJ7Kun1CEUTEHE1sNJYJpDIASi4ScQlQN6skIZosCnhtzyzCJDoOs9W75jQ5hvAFUI82aQUUDwATSiFSxnDfMW8/rkAQavG3w== matt910106@gmail.com 
      # 確保這裡的內容是你 ~/.ssh/id_rsa.pub 檔案中的完整內容

# 2. 執行命令：VM 啟動後要執行的命令
runcmd:
  - echo "--- Starting cloud-init setup for K3s Master ---"
  # 更新套件清單並安裝一些常用工具 (例如 curl 用於下載 K3s)
  - sudo apt update -y
  - sudo apt install -y curl vim git htop

  # 安裝 K3s Server
  # `K3S_KUBECONFIG_MODE="644"` 設定 Kubeconfig 檔案的權限，方便從本機讀取
  # `INSTALL_K3S_EXEC="--node-name k3s-master"` 設定節點名稱
  - echo "Installing K3s Server on k3s-master..."
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-name k3s-master --write-kubeconfig-mode 644" sh -

  # 等待 K3s 服務啟動 (可選，但有助於確保後續命令執行時服務已就緒)
  # - sleep 30

  - echo "--- K3s Master setup complete ---"